services:
  referencia:
    build:
      context: ./referencia
    container_name: referencia

  broker:
    build:
      context: ./broker
    container_name: broker
    depends_on:
      - referencia

  pubsub_proxy:
    build:
      context: ./proxy
    container_name: pubsub_proxy

  server1:
    build:
      context: ./server
    container_name: server1
    environment:
      - SERVER_ID=1
    volumes:
      - server1_data:/data
    depends_on:
      - broker
      - pubsub_proxy
      - referencia

  server2:
    build:
      context: ./server
    container_name: server2
    environment:
      - SERVER_ID=2
    volumes:
      - server2_data:/data
    depends_on:
      - broker
      - pubsub_proxy
      - referencia

  client1:
    build:
      context: ./client
    container_name: client1
    environment:
      - CLIENT_ID=bot1
      - BROKER_HOST=broker
      - PROXY_HOST=pubsub_proxy
    depends_on:
      - broker
      - pubsub_proxy

  client2:
    build:
      context: ./client
    container_name: client2
    environment:
      - CLIENT_ID=bot2
      - BROKER_HOST=broker
      - PROXY_HOST=pubsub_proxy
    depends_on:
      - broker
      - pubsub_proxy

volumes:
  server1_data:
  server2_data: